// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	filesys "sigs.k8s.io/kustomize/kyaml/filesys"

	mock "github.com/stretchr/testify/mock"

	resmap "sigs.k8s.io/kustomize/api/resmap"
)

// Renderer is an autogenerated mock type for the Renderer type
type Renderer struct {
	mock.Mock
}

// Run provides a mock function with given fields: fSys, path
func (_m *Renderer) Run(fSys filesys.FileSystem, path string) (resmap.ResMap, error) {
	ret := _m.Called(fSys, path)

	var r0 resmap.ResMap
	if rf, ok := ret.Get(0).(func(filesys.FileSystem, string) resmap.ResMap); ok {
		r0 = rf(fSys, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resmap.ResMap)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(filesys.FileSystem, string) error); ok {
		r1 = rf(fSys, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
