name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile=coverage.cov ./kustomize ./cache

    - name: Tests coverage
      uses: codecov/codecov-action@v2
      with:
        file: coverage.cov
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p . -n="kustomize" -u="https://api-horusec.zup.com.br"
