name: build compass

on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, ready_for_review]

permissions: read-all

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0